import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import ToastContainerComp from "@/components/common/toast-container-comp";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "ROI Monk",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark,
      }}
    >
      <html lang="en">
        <body className={inter.className}>
          {children}

          <ToastContainerComp />
        </body>
      </html>
    </ClerkProvider>
  );
}
